### ISSUE TITLE
Compiles but doesn't properly run. Boots to a solid white screen. 

### ISSUE THREAD

**Issue by RokHed19** [andreibobirica/Alfawise-U30-Marlin#2]
Compiles but doesn't properly run. Boots to a solid white screen.  There are multiple variants of the U30 / Lk4 that use different LCD screens. Likely you have not accounted for those.

**Comment by andreibobirica** [comment]
Hi, This is a tested and working version of the Marlin firmware for the Alfawise tested and modified by me.
I suggest you also look at my other repo with the firmware still for the U30 but slightly more updated.
https://github.com/andreibobirica/Marlin

If your screen is blank you need to be careful how you compile your firmware.
First of all, disable RELAYMULTIE, it is for a Dual Extrusion feature that I have created.
Subsequently in the file platformio.ini you find at line 911:
  -DU30 -DTS_V19
V11 for older printers
V12 for 2018 printers
V19 for printers of 2019 and 2020
Only the orientation of the touch screen changes.

As for the image, in the repo
https://github.com/andreibobirica/Marlin
find this option near line 911 these options:
  -DU30 -DTS_V19
  # -DLCD_READ_ID = 0x04
  -DLCD_READ_ID = 0xD3
if it appears white it switches between 04 and D3.
If you have an old printer I recommend V11 04.
If you have a new printer I recommend V12 D3 or V19 D3

This firmware has been tested for all screen versions and works perfectly, it is a fork of the Official Marlin with all the modifications of another guy, Tpruvot.

**Comment by andreibobirica** [comment]
I recommend you download the firmware from this other repo:
https://github.com/andreibobirica/Marlin
I keep it updated as it is the repo I work on.
I advise you to inquire about the active features on this firmware such as Mesh Bed Leveling or Linear Advance.
Careful, if you hold down on the red button, Abort the print.
there is an autostart print function, if it finds auto0.g file in the sd, printing starts.

Finally, I recommend that you try the pre-compiled firmware first to find out your version. (I'm in Italian)
Then once you find out, fill in your English version yourself.

Finally, I recommend that you take a look at my guide for the dual Extrusion for the U30.
https://drive.google.com/drive/folders/18Gvf3rcUjZQlO6g67my7TcCaHh5_63tr

**Comment by RokHed19** [comment]
Your precompiled project.bin V1.9 D3 works, but of course is in Italian. I need English.
I do not understand how to compile your source code with these options.
Using -DU30 -DTS_V19 in the source results in a white screen at boot.
How do you set the options for V19 D3?

Thanks

**Comment by andreibobirica** [comment]
You need to set V1.9
And the D3 version in Configuration.h ( if this repo) 
Or D3 version in platformio.ini( in the other repo) 
If you wait this evening i will compile it for you. 
In the future i will compile the major release ( of this repo) for all alfawise ita and eng too. 
Soon i will post in dropbox the version in english for you. 


Have you whatched the dual extrusion guide? What you think?

I will close this issue this evening when i will post you precompiled version of firmware.

**Comment by RokHed19** [comment]
I have it compiled now, thanks for the help.
I will review the dual guide later.

Thanks

**Comment by RokHed19** [comment]
I used your firmware for printing several items last night and it worked well, but this morning with no changes I tried printing some of the same prints and got very erratic behavior.  The speed was extremely high for unknown reasons causing the extruder to jam. Both retraction and extrusion appeared to be running at 2x or 3x normal speed and I had changed nothing.

I had to finish prints so I had to return to the 2.053 Marlin and have had no time to further investigate. Have you seen such an issue? Perhaps the EEPROM file got corrupted. I really don’t know. I ran out of time today.

Thanks

**Comment by andreibobirica** [comment]
I've never heard such a thing
To me, a similar error, an Eeprom bug, extruded less than half. 
I found out in the end that it was octoprint's fault and a plugin that read and wrote
With normal use of the printer from SD there should be no problem.
Did you check that the steps /mm were the same? Did the x/y axes also move much faster? You checked that you didn't press the buttons in the status screen? (increase the speed this).
It's the first time I've heard of a problem like this. I think it's the eeprom that's corrupt,
As soon as you can put the firmware back on, start using the eeprom, and put your settings back on 
When you have time try again and in case you are experiencing this problem send me more details in private on telegram https://t.me/bob99and
In case of a serious problem we should report it on the official marlin thread, mine is just a modified version (many of the changes are basic or 
For the management of the press all things are stock, and in the case of problems should be reported.

**Comment by RokHed19** [comment]
I will check into this more later. I had to revert to finish some critical prints. On Aug 27, 2020 12:13 PM, andreibobirica <notifications@github.com> wrote:
I've never heard such a thing
To me, a similar error, an Eeprom bug, extruded less than half.
I found out in the end that it was octoprint's fault and a plugin that read and wrote
With normal use of the printer from SD there should be no problem.
Did you check that the steps /mm were the same? Did the x/y axes also move much faster? You checked that you didn't press the buttons in the status screen? (increase the speed this).
It's the first time I've heard of a problem like this. I think it's the eeprom that's corrupt,
As soon as you can put the firmware back on, start using the eeprom, and put your settings back on
When you have time try again and in case you are experiencing this problem send me more details in private on telegram https://t.me/bob99and
In case of a serious problem we should report it on the official marlin thread, mine is just a modified version (many of the changes are basic or
For the management of the press all things are stock, and in the case of problems should be reported.
