### ISSUE TITLE
Abilitare un opzione in Configuration_adv.h

### ISSUE THREAD

**Issue by danielrama30** [andreibobirica/Alfawise-U30-Marlin#3]
Sarebbe possibile aver una build in .bin con un opzione abilitata? Dovrebbe essere una roba da nulla, avrei solo bisogno che nel file Configuration_adv.h venisse abilitata la riga "#define CNC_WORKSPACE_PLANES    // Allow G2/G3 to operate in XY, ZX, or YZ planes"?
Ho un progetto di tentare di convertire la U30 in una CNC e mi serve Marlin con quell'opzione abilitata, ma putroppo non avendo esperienza ne' con vscode e platformio, ne' con la compilazione e sviluppo di Marlin stesso sto avendo problemi a sfare e mi manca il tempo per mettermici a studiare e risolvere questi problemi.
È una richiesta un po' strana lo so.

**Comment by andreibobirica** [comment]
Ciao, contattami in privato su telegram a @bob99and
Possiamo poi risolvere la cosa

Il sab 25 dic 2021, 13:08 danielrama30 ***@***.***> ha
scritto:
